-- Drop existing foreign key constraints that reference auth.users
-- The names might be auto-generated by Postgres, so we find and drop them.
DO $
DECLARE
    con_name TEXT;
BEGIN
    -- For service_orders.approver_id
    SELECT conname INTO con_name
    FROM pg_constraint
    WHERE conrelid = 'public.service_orders'::regclass
      AND confrelid = 'auth.users'::regclass
      AND conname LIKE 'service_orders_approver_id_fkey%';
    IF con_name IS NOT NULL THEN
        EXECUTE 'ALTER TABLE public.service_orders DROP CONSTRAINT ' || quote_ident(con_name);
    END IF;

    -- For service_orders.created_by
    SELECT conname INTO con_name
    FROM pg_constraint
    WHERE conrelid = 'public.service_orders'::regclass
      AND confrelid = 'auth.users'::regclass
      AND conname LIKE 'service_orders_created_by_fkey%';
    IF con_name IS NOT NULL THEN
        EXECUTE 'ALTER TABLE public.service_orders DROP CONSTRAINT ' || quote_ident(con_name);
    END IF;

    -- For customers.created_by
    SELECT conname INTO con_name
    FROM pg_constraint
    WHERE conrelid = 'public.customers'::regclass
      AND confrelid = 'auth.users'::regclass
      AND conname LIKE 'customers_created_by_fkey%';
    IF con_name IS NOT NULL THEN
        EXECUTE 'ALTER TABLE public.customers DROP CONSTRAINT ' || quote_ident(con_name);
    END IF;

    -- For products.created_by
    SELECT conname INTO con_name
    FROM pg_constraint
    WHERE conrelid = 'public.products'::regclass
      AND confrelid = 'auth.users'::regclass
      AND conname LIKE 'products_created_by_fkey%';
    IF con_name IS NOT NULL THEN
        EXECUTE 'ALTER TABLE public.products DROP CONSTRAINT ' || quote_ident(con_name);
    END IF;
END;
$;


-- Add new foreign key constraints referencing the profiles table
ALTER TABLE public.service_orders
ADD CONSTRAINT service_orders_approver_id_fkey
FOREIGN KEY (approver_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.service_orders
ADD CONSTRAINT service_orders_created_by_fkey
FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.customers
ADD CONSTRAINT customers_created_by_fkey
FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE public.products
ADD CONSTRAINT products_created_by_fkey
FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

